config/routes.rb
Rails.application.routes.draw do
  resources :books
  get 'welcome/index'

root 'welcome#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
    validates :title, presence: true
    validates :isbn, uniqueness: true, length: {is:10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def new
  end
  def create
    @book = Book.new(book_params)
    if @book.save
    	redirect_to @book
    else
    	render 'new'
    end
#	render json: params[:book].inspect
  end
    def show
    	@book = Book.find(params[:id])
    end

	def index
		@books = Book.all
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			redirect_to books_path
		else
			render 'edit'
		end
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy

		redirect_to books_path
	end
    private
	def book_params
		params.require(:book).permit(:title, :isbn, :author, :description)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<%= form_for :book, url: books_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :isbn %><br>
    <%= f.text_field :isbn %>
  </p>
 
 <p>
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </p>
 
 <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/books/edit.html.erb
<h2>Edit Book Information</h2>
<%= render 'form' %>
<%= link_to 'Back To Books', books_path %>

app/views/books/index.html.erb
<h2>Listing All Books</h2>
<table>
    <% b = Book.all %>
	<% if b.length == 0 %>
	    <em>No books found!</em>
	<% else %>
	<tr>
		<th>Title</th>
		<th>ISBN</th>
		<th>Author</th>
		<th>Description</th>
	</tr>
    	<% @books.each do |book| %>
    		<tr>
    			<td><%=book.title %></td>
    			<td><%=book.isbn %></td>
    			<td><%=book.author %></td>
    			<td><%=book.description %></td>
    			<td><%= link_to 'Show', book_path(book) %></td>
    			<td><%= link_to 'Edit', edit_book_path(book) %></td>
    			<td><%= link_to 'Delete', book_path(book), method: :delete, data: { confirm: "Are You Sure?" } %></td>
    		</tr>
    	<% end %>
    <% end %>
</table>
<%= link_to 'Home', root_path %> |
<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>
<%= render 'form' %>
<%= link_to 'Books List', books_path %>

app/views/books/show.html.erb
<h2>Show the Book</h2>
<p>
	<strong>Title: </strong>
	<%= @book.title %>
</p>
<p>
	<strong>ISBN: </strong>
	<%= @book.isbn %>
</p>
<p>
	<strong>Author: </strong>
	<%= @book.author %>
</p>
<p>
	<strong>Description: </strong>
	<%= @book.description %>
</p>
<%= link_to 'Books List', books_path %> | 
<%= link_to 'Edit Book', edit_book_path(@book) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Library-Books Management</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome to the Libray</h1>
<p>Feel free to play around</p>
<%= link_to 'Library', books_path %>